# Generated by Django 4.1.5 on 2023-02-03 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hotel_Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Software_Regist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.DateTimeField()),
                ('Details', models.TextField()),
                ('License_Type', models.TextField()),
                ('License_User', models.TextField()),
                ('License_Number', models.TextField()),
                ('First_use_datetime', models.DateTimeField()),
                ('Start_use_datetime', models.DateTimeField()),
                ('End_use_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PositionID', models.IntegerField()),
                ('Name', models.TextField()),
                ('LastName', models.TextField()),
                ('Department', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regist_datetime', models.DateTimeField()),
                ('Number_item', models.TextField()),
                ('Type', models.TextField()),
                ('Type_details', models.TextField()),
                ('OS', models.TextField()),
                ('Software', models.CharField(max_length=100)),
                ('Status', models.TextField()),
                ('PositionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.user_manage')),
            ],
        ),
    ]
