# Generated by Django 4.1.5 on 2023-02-03 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='User_Manage',
        ),
    ]
