# Generated by Django 4.1.5 on 2023-02-03 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_delete_items_delete_user_manage'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PositionID', models.IntegerField()),
                ('Name', models.TextField()),
                ('LastName', models.TextField()),
                ('Department', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regist_datetime', models.DateTimeField()),
                ('Number_item', models.TextField()),
                ('Type', models.TextField()),
                ('Type_details', models.TextField()),
                ('OS', models.TextField()),
                ('Software', models.CharField(max_length=100)),
                ('Status', models.TextField()),
                ('PositionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.user_manage')),
            ],
        ),
    ]
