# Generated by Django 4.1.5 on 2023-02-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_user_manage_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Software_Regist',
        ),
    ]
