# Generated by Django 4.1.5 on 2023-02-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_software_regist'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Register', models.DateTimeField()),
                ('Date_Act_Notice', models.DateTimeField()),
                ('Date_Act_Use', models.DateTimeField()),
                ('Act_Name', models.CharField(max_length=100, verbose_name='Enter Act Name')),
                ('Act_Type', models.TextField()),
                ('Act_Status', models.TextField()),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'act_pdf',
            },
        ),
    ]
