# Generated by Django 4.1.5 on 2023-02-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_uploadfileform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFileForm',
        ),
    ]
